services:
  discord-bot:
    build: 
      context: .
    container_name: discord-bot
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - API_KEY=${API_KEY}
